[package]
name = "primes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
